# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel:
        build:
            context: ./
            dockerfile: Dockerfile.prod
        expose:
            - "80"
        depends_on:
            - mysql
        environment: 
            VIRTUAL_HOST: api.listed.mdomzalski.pl,www.api.listed.mdomzalski.pl
            LETSENCRYPT_HOST: api.listed.mdomzalski.pl,www.api.listed.mdomzalski.pl
        restart: always
        networks:
            - listed
    mysql:
        image: 'mysql:8.0'
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'db_data:/var/lib/mysql'
        restart: always
        networks:
            - listed
volumes:
    db_data:

networks:
    listed:
        driver: bridge
    default:
        external:
            name: nginx-proxy
