version: '3'
services:
  api_listed:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    expose:
      - 80
    restart: always
    container_name: api.listed.mdomzalski.pl
    volumes:
      - /vendor
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-listed.rule=Host(`api.listed.mdomzalski.pl`,`www.api.listed.mdomzalski.pl`)"
      - "traefik.http.routers.api-listed.entrypoints=websecure"
      - "traefik.http.routers.api-listed.tls.certresolver=production"
      - "traefik.http.routers.api-listed-https.tls=true"
      - "traefik.http.routers.api-listed-https.rule=Host(`api.listed.mdomzalski.pl`,`www.api.listed.mdomzalski.pl`)"
      - "traefik.http.routers.api-listed-https.entrypoints=websecure"
      - "traefik.http.routers.api-listed-https.service=api-listed"
      - "traefik.http.services.api-listed.loadbalancer.server.port=80"

networks:
  default:
    name: traefik
    external: true

